### ISSUE TITLE
Update Clans to NBGL NeverBack Family

### ISSUE THREAD

**Issue by sanjuand** [cr-api/cr-api-ux#16]
Hi, Is it possible update family clans of NeverBack?? 

Thank You in advance

  - name: NeverBack Gaming Ladder
    key: nbgl
    color: red
    emblem: flag_j_02
    info:
      logo: /static/img/brands/logo/nbgl.png
      description: >
        The **NeverBack Gaming Ladder Clan Family** (NBGL) consists of a lot of trophy-pushing clans.

        Our clan family is home to NeverBack Gaming Team of Clash Royale’s greatest tournament players on Europe Zone, and NeverBack Latam to Latino America players.
        and revelation Team of first season of SuperLiga Orange in Spain (SLO LVP).
        Every clan in our family finishees the clan crown chest early every time.
      social:
        - twitter: https://twitter.com/NeverBackLadder
        - discord: https://discord.gg/nmh7wFn
    clans:
      - name: NeverBack
        tag: 8R28VQ9P
      - name: NeverBack Alpha
        tag: 89YV8UR8
      - name: NeverBack Betta
        tag: 88LL8GYJ
      - name: NeverBack Gamma
        tag: 88QUQGGU
      - name: NeverBack Delta
        tag: 8VQCL0CQ
      - name: NeverBack NKZ L
        tag: 8CLPUJU0
      - name: NeverBack Latam
        tag: 98J98PU8
      - name: NeverBackLatam2
        tag: 9LYUU92L

**Comment by smlbiobot** [comment]
please remember to escape your config when posting — add three back ticks:

```yaml
  - name: NeverBack Gaming Ladder
    key: nbgl
    color: red
    emblem: flag_j_02
    info:
      logo: /static/img/brands/logo/nbgl.jpg
      description: >
        The **NeverBack Gaming Ladder Clan Family** (NBGL) consists of a lot of trophy-pushing clans.

        Our clan family is home to NeverBack Gaming Team of Clash Royale’s greatest tournament players on Europe Zone, and NeverBack Latam to Latino America players.
        and revelation Team of first season of SuperLiga Orange in Spain (SLO LVP).
        Every clan in our family finishees the clan crown chest early every time.
      social:
        - twitter: https://twitter.com/NeverBackLadder
        - discord: https://discord.gg/c7BDRzc
    clans:
      - name: NeverBack
        tag: 8R28VQ9P
      - name: NeverBack Alpha
        tag: 89YV8UR8
      - name: NeverBack Betta
        tag: 88LL8GYJ
      - name: NeverBack Gamma
        tag: 88QUQGGU
      - name: NeverBack Delta
        tag: 8VQCL0CQ
      - name: NeverBack NKZ L
        tag: 8CLPUJU0
      - name: NeverBack Latam
        tag: 98J98PU8
      - name: NeverBackLatam2
        tag: 9LYUU92L
```
