### ISSUE TITLE
Team CMC Clan Family

### ISSUE THREAD

**Issue by ZeNeLLiE** [cr-api/cr-api-ux#27]
```yaml
- name: Team CMC Clan Family
    key: cmc
    color: orange
    emblem: Twin_Peaks_02
    info:
      logo: https://www.teamcmc.pro/css/img/logo-cmc.png
      description: >
        **Team CMC (short for Chan Mali Chan)** is a Singapore based family clan with all our clans 
        within  the Top 100 locally.

        We pride ourselves in clashing hard (Monthly Tournaments, Intra-Family League) and clashing the 
        right way (NO BM-ing allowed).

        Our players have done well in local competitions placing in local live tournaments!

        Chan Mali Chan hoi HOI~

      social:
        - twitter: https://twitter.com/TeamCMCGG
        - facebook: https://www.facebook.com/TeamChanMaliChan/
        - website: https://www.teamcmc.pro
    clans:
      - name: Team CMC
        tag: 80YJV0UP
      - name: Team CMC²
        tag: 2VV8CCG2
      - name: Team CMC³
        tag: 8U9LP2RJ
      - name: Team CMC⁴
        tag: 8YQURUQC
      - name: Team CMC⁵
        tag: 8YPJVYRR
     
```

**Comment by smlbiobot** [comment]
Implemented http://royaleapi.com/clan/family/cmc

```yaml
  - name: Team CMC Clan Family
    key: cmc
    color: orange
    emblem: Twin_Peaks_02
    info:
      logo: /static/img/brands/logo/cmc.png
      description: >
        **Team CMC (short for Chan Mali Chan)** is a Singapore based family clan with all our clans
        within  the Top 100 locally.

        We pride ourselves in clashing hard (Monthly Tournaments, Intra-Family League) and clashing the
        right way (NO BM-ing allowed).

        Our players have done well in local competitions placing in local live tournaments!

        Chan Mali Chan hoi HOI~

      social:
        - twitter: https://twitter.com/TeamCMCGG
        - facebook: https://www.facebook.com/TeamChanMaliChan/
        - website: https://www.teamcmc.pro
    clans:
      - name: Team CMC
        tag: 80YJV0UP
      - name: Team CMC²
        tag: 2VV8CCG2
      - name: Team CMC³
        tag: 8U9LP2RJ
      - name: Team CMC⁴
        tag: 8YQURUQC
      - name: Team CMC⁵
        tag: 8YPJVYRR
```
