### ISSUE TITLE
Family Royal~Arrow

### ISSUE THREAD

**Issue by PtitMaxRA** [cr-api/cr-api-ux#31]
```yaml
  - name: Reddit Alpha Clan Family
    key: ra
    color: red
    emblem: Arrow_02.png
    info:
      description: >
        La famille **Royal~Arrow** consiste en 3 clans aux objectifs différents.

        Le premier clan a pour objectif le top fr, et se classe régulièrement dans le top 200 fr 
        Royal~Arrow 2 a un objectif familial et est le vivier du clan 1
        Royal~Arrow 3 est le plus actif et est également vivier du clan 1.
        
        Les 3 clans sont français et recrute des joueurs français à respectivement 4100, 3600 et 3400 trophées.
      social:
        - line: ptitmax
        - discord: https://discord.gg/W2qpEca
      clans:
        - name: Royal~Arrow
          tag: 22GQU9U
        - name: Royal~Arrow 2
          tag: VYVGUUY
        - name: Royal~Arrow 3
          tag: 98Y2089C
```
