### ISSUE TITLE
To Incorporate the NeverBack Ladder Family Clans to CR-API views

### ISSUE THREAD

**Issue by sanjuand** [cr-api/cr-api-ux#7]
```yaml
  - name: NeverBack Gaming Ladder
    key: nbgl
    color: red
    emblem: flag_j_02
    info:
      logo: https://pbs.twimg.com/profile_images/953754415751680001/FAc1dWz9_normal.jpg
      description: >
        The **NeverBack Gaming Ladder Clan Family** (NBGL) consists of a lot of trophy-pushing clans.

        Our clan family is home to NeverBack Gaming Team of Clash Royale’s greatest tournament players on Europe Zone,
        and revelation Team of first season of SuperLiga Orange in Spain (SLO LVP).
        Every clan in our family must finished the clan crown chest early every time.
      social:
        - twitter: https://twitter.com/NeverBackLadder
        - discord: https://discord.gg/c7BDRzc
        - website: under construction
    clans:
      - name: NeverBack
        tag: 8R28VQ9P
      - name: NeverBack Alpha
        tag: 89YV8UR8
      - name: NeverBack Betta
        tag: 88LL8GYJ
      - name: NeverBack Gamma
        tag: 88QUQGGU
      - name: NeverBack NKZ L
        tag: 8CLPUJU0
```

**Comment by smlbiobot** [comment]
please escape config as I did (click edit and see how I did it)

Meanwhile your description contains a typo. Can you clarify if it is a typo or not:

> Team of **firts** Season

**Comment by smlbiobot** [comment]
@sanjuand 

1. Please escape config as I did (click edit and see how I did it)

2. Your description contains a typo. Can you clarify if it is a typo or not:

> Team of **firts** Season 

3. Key must be all lowercase.

4. Linking channels to discord won’t work — please create a never expired server invite or use http://discord.me to create a vanity URL

**Comment by sanjuand** [comment]
thanx for your response, I review the petition and resolve the problems, when I finish it, I will let you know

**Comment by sanjuand** [comment]
All issues resolved in the petition, thanx

**Comment by smlbiobot** [comment]
@sanjuand Grammatical mistakes:

> Every clan in our family must finished the clan crown chest early every time.

Suggested edits:

1. Every clan in our family must finish the clan crown chest early every time.
2. Every clan in our family finishes the clan crown chest early every time.

Option 2 would be better. Option 1 will imply that you are required to finish the clan chest early but how do you enforce that?

**Comment by smlbiobot** [comment]
Website under construction is not an option. I will remove. You can re-submit another request (or re-open this issue when you are ready to put one here.

Final edits:

```yaml
  - name: NeverBack Gaming Ladder
    key: nbgl
    color: red
    emblem: flag_j_02
    info:
      logo: /static/img/brands/logo/nbgl.png
      description: >
        The **NeverBack Gaming Ladder Clan Family** (NBGL) consists of a lot of trophy-pushing clans.

        Our clan family is home to NeverBack Gaming Team of Clash Royale’s greatest tournament players on Europe Zone,
        and revelation Team of first season of SuperLiga Orange in Spain (SLO LVP).
        Every clan in our family finishees the clan crown chest early every time.
      social:
        - twitter: https://twitter.com/NeverBackLadder
        - discord: https://discord.gg/c7BDRzc
    clans:
      - name: NeverBack
        tag: 8R28VQ9P
      - name: NeverBack Alpha
        tag: 89YV8UR8
      - name: NeverBack Betta
        tag: 88LL8GYJ
      - name: NeverBack Gamma
        tag: 88QUQGGU
      - name: NeverBack NKZ L
        tag: 8CLPUJU0
```

The logo link you gave me is rather low-resolution and I have downloaded the higher res one from your Twitter.
